config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"
  get 'about', to: 'pages#about'
  get 'employee', to: 'pages#employee'
  get 'contact', to: 'pages#contact'
  get 'prices', to: 'pages#prices'
  resources :pets
end

app/models/pet.rb
class Pet < ApplicationRecord
   belongs_to :user
   has_one_attached :image
    validates :title, presence: true, length: {minimum: 3, maximum: 20}
    validates :owner, presence: true
    validates :date_in, presence: true
    validates :date_out, presence: true
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource
  # GET /pets or /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1 or /pets/1.json
  def show
  end

  # GET /pets/new
  def new 
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets or /pets.json
  def create
    @pet = Pet.new(pet_params)

    if current_user.admin? # Check if the current user is an admin
      user = User.find_by(email: params[:pet][:owner_email])

      if user
        @pet.owner_id = user.id
      else
        # Handle case where user with provided email doesn't exist
        # Redirect or display an error message
      end
    else
      @pet.owner_id = current_user.id # For regular users, assign the current user's ID
    end

    respond_to do |format|
      if @pet.save
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully created." }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1 or /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully updated." }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1 or /pets/1.json
  def destroy
    @pet.destroy

    respond_to do |format|
      format.html { redirect_to pets_url, notice: "Pet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:title, :image, :owner, :owner_id, :breed, :age, :weight, :medicins, :food, :date_in, :date_out, :keeper, :description, :vaccinated)
    end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<div class= "container">
  <div class= "row justify-content-center">
  <div class= "col-8">
  <%= render 'shared/errors' %>
  <%= form_with(model: pet) do |form| %>
      <div class="form-group-row mb-3">
        <%= form.label :title, 'Imię psa: *', class: "col-2 col-form-label" %>
        <div class="col-sm">
          <%= form.text_field :title, class: "form-control" %>
        </div>
      </div>
    
      <div class="form-group-row mb-3">
      <%= form.label :image, 'Zdjęcie:', class: "col-2 col-form-label" %>
      <div class="col-sm">
        <%= form.file_field :image, class: "form-control" %>
      </div>
    </div>

    <div class="form-group-row mb-3">
    <%= form.label :owner, 'Wlaściciel: *', class: "col-2 col-form-label" %>
    <div class="col-sm">
      <%= form.text_field :owner, class: "form-control" %>
    </div>
    </div>

    <div class="form-group-row mb-3">
    <%= form.label :owner_id, 'ID Wlaściciela:', class: "col-2 col-form-label" %>
    <div class="col-sm">
      <%= form.number_field :onwer_id, class: "form-control" %>
    </div>
    </div>

    <div class="form-group-row mb-3">
    <%= form.label :breed, 'Rasa:', class: "col-2 col-form-label" %>
    <div class="col-sm">
      <%= form.text_field :breed, class: "form-control" %>
    </div>
    </div>

    <div class="form-group-row mb-3">
    <%= form.label :age, 'Wiek(w latach):', class: "col-2 col-form-label" %>
    <div class="col-sm">
      <%= form.number_field :age, class: "form-control" %>
    </div>
    </div>

    <div class="form-group-row mb-3">
    <%= form.label :weight, 'Waga (kg):', class: "col-2 col-form-label" %>
    <div class="col-sm">
      <%= form.number_field :weight, class: "form-control" %>
    </div>
    </div>

    <div class="form-group-row mb-3">
    <%= form.label 'Czy szczepiony?', class: "col-2 col-form-label" %>
    <div class="col-sm">
    <div class="field">
    <%= form.radio_button :vaccinated, true %>
    <%= form.label :vaccinated, 'Tak' %>
  </div>
  
  <div class="field">
    <%= form.radio_button :vaccinated, false %>
    <%= form.label :vaccinated, 'Nie' %>
  </div>
    </div>
    </div>

    <div class="form-group-row mb-3">
    <%= form.label :medicins, 'Leki:', class: "col-2 col-form-label" %>
    <div class="col-sm">
      <%= form.text_field :medicins, class: "form-control" %>
    </div>
    </div>

    <div class="form-group-row mb-3">
    <%= form.label :food, 'Preferowana karma:', class: "col-3 col-form-label" %>
    <div class="col-sm">
      <%= form.text_field :food, class: "form-control" %>
    </div>
    </div>

    <div class="form-group-row mb-3">
    <%= form.label :date_in, 'Pobyt od: *', class: "col-2 col-form-label" %>
    <div class="col-sm">
      <%= form.date_field :date_in, class: "form-control" %>
    </div>
    </div>

    <div class="form-group-row mb-3">
    <%= form.label :date_out, 'Pobyt do: *', class: "col-2 col-form-label" %>
    <div class="col-sm">
      <%= form.date_field :date_out, class: "form-control" %>
    </div>
    </div>

    <div class="form-group-row mb-3">
    <%= form.label :keeper, 'Opiekun:', class: "col-2 col-form-label" %>
    <div class="col-sm">
      <%= form.text_field :keeper, class: "form-control" %>
    </div>
    </div>

    <div class="form-group-row mb-3">
    <%= form.label :description, 'Komentarz:', class: "col-2 col-form-label" %>
    <div class="col-sm">
      <%= form.text_area :description, rows: 5, class: "form-control" %>
    </div>
    </div>
    <div class="warning-box">
    <p style="color: white;">Pola oznaczone gwiazdką nie mogą być puste</p>
  </div>
    <div class="button-center">
      <%= form.submit class: "btn btn-outline-success btn-lg"%>
    </div>
    <% end %>
  </div>
  
      
    </div>

</div>

app/views/pets/_pet.html.erb
<h1 class="text-center mt-4">Szczegóły:</h1>

<div id="<%= dom_id pet %>">
<div class="card mt-4">
<%= image_tag @pet.image if @pet.image.attached? %>
  <div class="card-body">
    <h5 class="card-title text-center"><%= pet.title %></h5>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Imię: <%=pet.title %></li>
    <li class="list-group-item">Wlaściciel: <%=pet.owner %></li>
    <li class="list-group-item">Rasa Psa: <%=pet.breed %></li>
    <li class="list-group-item">Wiek (lata): <%=pet.age %></li>
    <li class="list-group-item">Waga (kg): <%=pet.weight %></li>
    <li class="list-group-item">Szczepiony?: 
    <% if @pet.vaccinated? %>
    Tak
    <% else %>
    Nie
    <% end %>
    </li>
    <li class="list-group-item">Lekarstwa: <%=pet.medicins %></li>
    <li class="list-group-item">Karma: <%=pet.food %></li>
    <li class="list-group-item">Zameldowanie: <%=pet.date_in.strftime("%d-%m-%Y") %></li>
    <li class="list-group-item">Wymeldowanie: <%=pet.date_out.strftime("%d-%m-%Y") %></li>
    <li class="list-group-item">Opiekun: <%=pet.keeper %></li>
    <li class="list-group-item">Komentarz: <%=simple_format(pet.description) %></li>

  </ul>
  <div class="card-body">
  <div class="center-link">
  <%= link_to "Edytuj", edit_pet_path(@pet) %> |
  <%= link_to "Powrót do zameldowanych", pets_path %>
  </div>
  <div class="button-center ">
  <%= button_to "Wymelduj/Usuń", @pet, method: :delete, class: "btn btn-danger"  %>
  </div>
  </div>
</div>

</div>

app/views/pets/edit.html.erb
  <h1 class="text-center mt-4">Edycja:</h1>


<%= render "form", pet: @pet %>

<div class="center-link">
  <%= link_to "Cofnij do wyświetlania", @pet %>
</div>

app/views/pets/index.html.erb
  <h1 class="text-center mt-4">Dostępne zwierzaki:</h1>
  <div class="container">
  <% @pets.each do |pet| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header fst-italic">
          Opiekun: <%= pet.keeper %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to pet.title, pet_path(pet), class: "text-success" %></h5>
            <p class="card-text">Właściciel: <%= pet.owner %></p>
            <%= link_to "Szczegóły", pet_path(pet), class: "btn btn-outline-success" %>
            <%= link_to "Edycja", edit_pet_path(pet), class: "btn btn-outline-info" %>
            
          </div>
          <div class="card-footer text-muted">
          <small>Pobyt od: <%= pet.date_in %><br/>
          Pobyt do: <%= pet.date_out %> </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  
</div>
<div class="center-link">
  <%= link_to "Zamelduj kolejnego gościa", new_pet_path %>
  </div>

app/views/pets/new.html.erb
  <h1 class="text-center mt-4">Check in:</h1>

<%= render "form", pet: @pet %>
<div class="center-link">
<%= link_to 'Lista zamedeldowanych', pets_path %>
</div>

app/views/pets/show.html.erb
<%= render @pet %>