config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"
  get 'about', to: 'pages#about'
  get 'employee', to: 'pages#employee'
  get 'contact', to: 'pages#contact'
  get 'prices', to: 'pages#prices'
  resources :pets
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
    <div class="containter text-center">
        <small>Copyright &copy; <%=link_to "Damian Czarnota", root_path, class: "text-white" %></small>
        </div>
</footer>        

app/views/layouts/_messages.html.erb
<div class='text-center'>
    <% flash.each do |name, msg| %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
  <%= link_to "Pet Hotel", root_path, class: "navbar-brand", id: "logo" %> 
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "O nas", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Opiekunowie", employee_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Hotel
          </a>
          <ul class="dropdown-menu">
            <%= link_to "Zamelduj nowego podopiecznego", new_pet_path, class: "dropdown-item" %>
            <%= link_to "Zobacz zameldowanych", pets_path, class: "dropdown-item" %>
            <li><hr class="dropdown-divider"></li>
            <%= link_to "Cennik", prices_path, class: "dropdown-item" %>
          </ul>
        </li>
        <li class="nav-item">
        <%= link_to "Kontakt", contact_path, class: "nav-link" %>
        </li>
      </ul>
      
  <ul class="navbar-nav">
    <% if current_user %>
      <li class="nav-item"><%= link_to "Edytuj konto", edit_user_registration_path, class:"nav-link" %></li>
      <li class="nav-item"><%= button_to "Wyloguj się", destroy_user_session_path, method: :delete, class:"btn btn-small btn primary mx-2" %></li>
        <% else %>
      <li class="nav-item"><%= link_to "Rejestracja użytkownika", new_user_registration_path, class:"nav-link" %></li>
      <li class="nav-item"><%= link_to "Logowanie", new_user_session_path, class:"nav-link" %></li>
    <% end %>
  </ul>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pet Hotel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  </head>

  <body class="d-flex flex-column">

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <%= render 'layouts/navigation' %>
  <div id="page-content">
  <%= render 'layouts/messages' %>
    <%= yield %>
   </div>
    <%= render 'layouts/footer' %>

  </body>
</html>